# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fd94a73510d6169556f4876c03eef0223fe1b11290d0fde41907c5330f4f4abf869e0abf0a7f2c3b56d1ae0788ba57e10f352284b676fc372fdfe2772490b3b

test:
  secret_key_base: 80994654e15ba70a96b26912182f374fdfeb241560b46f3f11dc46f275b16da75dbfbc85c25d54e053a9f4e5ebefb7270b6f65fd00d058a13a6f206943b864ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
